name:                crypto-trading-bot
version:             0.1.0.0
github:              githubuser/crypto-trading-bot
license:             BSD-3-Clause
author:              Author name here
maintainer:          example@example.com
copyright:           2026 Author name here

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/crypto-trading-bot#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0
- websockets
- wuss              # Secure WebSockets (wss://)
- aeson             # JSON parsing
- async             # Concurrency utilities
- text
- stm               # Software Transactional Memory
- containers        # Data.Sequence and other collections
- retry

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  crypto-trading-bot-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - crypto-trading-bot
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  crypto-trading-bot-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - crypto-trading-bot
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
